// src/app/config/tabla-config.ts
export const TABLA_CONFIG: any = {
  generador: {
    encabezados: [
      'ID',
      'Tipo Documento',
      'Número Documento',
      'Primer Nombre',
      'Segundo Nombre',
      'Primer Apellido',
      'Segundo Apellido',
      'Razón Social',
      'Dirección',
    ],
    campos: [
      'id',
      'tipoDocumento',
      'numeroDocumento',
      'primerNombre',
      'segundoNombre',
      'primerApellidos',
      'segundoApellido',
      'razonSocial',
      'direccion',
    ],
  },

  transportador: {
    encabezados: [
      'ID',
      'Tipo Documento',
      'Número Documento',
      'Primer Nombre',
      'Segundo Nombre',
      'Primer Apellido',
      'Segundo Apellido',
      'Razón Social',
      'Dirección',
    ],
    campos: [
      'id',
      'tipoDocumento',
      'numeroDocumento',
      'primerNombre',
      'segundoNombre',
      'primerApellidos',
      'segundoApellido',
      'razonSocial',
      'direccion',
    ],
  },

  receptor: {
    encabezados: [
      'ID',
      'Tipo Documento',
      'Número Documento',
      'Primer Nombre',
      'Segundo Nombre',
      'Primer Apellido',
      'Segundo Apellido',
      'Razón Social',
      'Dirección',
    ],
    campos: [
      'id',
      'tipoDocumento',
      'numeroDocumento',
      'primerNombre',
      'segundoNombre',
      'primerApellidos',
      'segundoApellido',
      'razonSocial',
      'direccion',
    ],
  },
  vehiculo: {
    encabezados: [
      'Código Vehículo',
      'Placa Vehículo',
      'Modelo',
      'Capacidad',
      'Fecha Expedición PIN',
      'Fecha Vencimiento PIN',
      'Transportador',
      'PIN',
    ],
    campos: [
      'id',
      'placaVehiculo',
      'modelo',
      'capacidad',
      'fechaExpedicionPIN',
      'fechaVencimientoPIN',
      'nombreTransportador',
      'pin',
    ],
  },

  reportesRCD: {
    encabezados: [
      'ID',
      'Fecha Reporte',
      'Tipo Reporte',
      'Volumen Estimado',
      'Documento',
      'ID Proyecto',
      'Transportador',
      'Receptor',
    ],
    campos: [
      'id',
      'fechaReporte',
      'reportesRCD',
      'volumenEstmRCD',
      'documento',
      'idProyecto',
      'transportador_idtransportador',
      'idreceptor',
    ],
  },
  resolucion: {
    encabezados: ['ID', 'Número', 'Ubicación', 'Actividad', 'Tipo', 'Inicio', 'Fin', 'PIN'],
    campos: [
      'id',
      'numeroResolucion',
      'ubicacion',
      'naturalezaActividad',
      'tipoAprovechamiento',
      'fechaInicio',
      'fechaFin',
      'pin',
    ],
  },
  proyecto: {
    encabezados: [
      'Código',
      'Nombre del Proyecto',
      'Dirección',
      'Fecha Inicio',
      'Fecha Fin',
      'Estado del Proyecto',
      'Generador',
      'PIN',
    ],
    campos: [
      'id',
      'nombre',
      'ubicacion',
      'fechaInicio',
      'fechaFin',
      'estadoProyecto',
      'titularLicUrb',
      'pin',
    ],
  },
  visitatecnica: {
    encabezados: [
      'Código Visita',
      'Fecha Creación',
      'Estado',
      'Fecha Visita',
      'Técnico Asignado',
      'Estado del Proyecto',
      'Proyecto',
      'Observaciones',
      'Acta',
    ],
    campos: [
      'id',
      'fechaCreacion',
      'estado',
      'fechaVisita',
      'idTecnico',
      'estadoProyecto',
      'proyecto.nombre',
      'observaciones',
      'acta',
    ],
  },
  reporte: {
    encabezados: [
      'Código Reporte',
      'Proyecto',
      'Fecha Presentación',
      'Fecha Inicio',
      'Fecha Final',
      'RCD Susceptibles Aprovech. (t)',
      'RCD No Susceptibles Aprovech. (t)',
      'Meta Aprovech. Total (t)',
      'Meta Aprovech. Total (%)',
    ],
    campos: [
      'id',
      'proyecto.nombre',
      'fechapresentacionreporte',
      'fechainicioreporte',
      'fechafinalreporte',
      'rcd_sus_apro_total',
      'rcd_no_sus_apro_total',
      'meta_total_tonelada',
      'meta_total_porcentaje',
    ],
  },
    usuarios: {
    encabezados: [
      'ID',
      'Usuario',
      'Nombre',
      'Email',
      'Estado',
      'Rol'
    ],
    campos: [
      'id',
      'usuario',
      'nombre',
      'email',
      'estado',
      'rol'
    ],
  },
  
};
